- geopolars/src/geodataframe.rs
- geopolars/src/geoseries.rs
- py-geopolars/src/lib.rs
This PR adds a convex_hull function for GeoSeries and GeoDataFrames.
The function is implemented for the follow GeoSeries types
- MultiPoint 
- MultiPolygon
- Polygon
- LineString 
- MultiLineString
Added test for MultiPoint case
> Adds convex_hull to geoseries and geodataframe

- geopolars/src/geoseries.rs
- py-geopolars/src/lib.rs
This adds the haversine, euclidean and geodesic length methods to the GeoSeries. 
For Polygons, MultiPolygons, Rects and Triangles, the methods calculate the total length of the exterior rings 
For Lines / MutliLines and LineStrings it returns the total length of the lines
For Points / MultiPoints it returns 0 as they technically have 0 length (this is what GeoPandas does as well)
It returns an error for GeometryCollections.
This should resolve #30
> Adding 2 length methods to GeoSeries

- Cargo.lock
- geopolars/Cargo.toml
- geopolars/src/geoseries.rs
Adds affine transform methods from Geo to the GeoSeries 
Mehods added 
- translate 
- rotate
- skew
- scale
- affine_transform
Notes: 
- Added a Transform Origin to allow easy specification of the origin of a transform for those that accept one. 
- Currently the arguments of a transform are specified only by manual values. It would be great if you could specify another Series for these as well so that each geometry would be transformed according to the parameters in that series.
- The current implementation does not work in-place, we might want to have another set of functions to do the transforms in-place, updating the geometry column with the new geoms 
- Currently there is no method to chain together transforms, instead I would advise people compose the transform using methods from the …
> Adding affine transform methods to GeoSeries

- Cargo.lock
- geopolars/Cargo.toml
- geopolars/src/geoseries.rs
Switching to use the exported versions of arrow2 components rather than using an explicit dependency on arrow2. This will mean that when polars updates arrow we should be in sync.
Resolves #49
> Switching to using polars exports for arrow rather than explicit dep

- py-geopolars/Cargo.lock
- py-geopolars/cargo.toml
- py-geopolars/src/ffi.rs
Same idea as #51. We probably needed to bump polars in both the Rust and Python bindings at the same time. Maybe fix the Python builds, ref #52
> [Python]: Bump polars; import arrow2 from polars exports

- .github/workflows/python.yml
- .github/workflows/rust.yml
- py-geopolars/Cargo.lock
The Python bindings currently fail to build; we should be running `cargo check` for both Python and Rust on every PR I think
> Add cargo check to CI

- Cargo.lock
- geopolars/Cargo.toml
- geopolars/src/geoseries.rs
- py-geopolars/Cargo.lock
- py-geopolars/cargo.toml
- py-geopolars/pyproject.toml
Testing publish with an alpha version:
- Crates.io (`cargo publish`): https://crates.io/crates/geopolars
- docs.rs: https://docs.rs/geopolars
- Pypi (`maturin publish`): https://pypi.org/project/geopolars/
Figured it was about time to reserve the `geopolars` name
> Python: Set to alpha version; test publishing

- py-geopolars/pyproject.toml
Closes https://github.com/kylebarron/geopolars/issues/46. 
Ref:
- https://maturin.rs/#python-metadata
- https://peps.python.org/pep-0621/
> Python: Update python package metadata

- Cargo.lock
- geopolars/Cargo.toml
- geopolars/src/geoseries.rs
- py-geopolars/Cargo.lock
- py-geopolars/Cargo.toml
- py-geopolars/src/lib.rs
- Proj is added under a feature flag named `proj`
- `to_crs` method added to the trait and implementation
- Includes both `&from` and `&to` because we don't have a way to store ancillary metadata on the polars objects yet. Hopefully this will be alleviated in the future if polars supports extension types
- So this doesn't handle metadata _tracking_ at this point
> Reprojection via proj

- Cargo.lock
- geopolars/Cargo.toml
- geopolars/src/error.rs
- geopolars/src/geodataframe.rs
- geopolars/src/geoseries.rs
- geopolars/src/lib.rs
- geopolars/src/main.rs
- py-geopolars/Cargo.lock
- py-geopolars/Cargo.toml
- py-geopolars/src/error.rs
- py-geopolars/src/lib.rs
- Create `GeopolarsError` enum in the main crate and `PyGeopolarsError` in the python crate
- Implement `From` so that we can use `?` more broadly
- Implement Python exceptions [as in py-polars](https://github.com/pola-rs/polars/blob/affbeb8f5f920600c40c0ce4c51f89a3c337194d/py-polars/src/error.rs#L56-L62)
- Propagate proj errors in `to_crs`, ref https://github.com/kylebarron/geopolars/pull/62#discussion_r922521616
> Improved error handling

- geopolars/src/util.rs
- Change `geom_at_index` to use `series.get(index)` rather than iterating over the entire series. Using `nth` on an iterator is `O(n)` instead of `O(1)` because it needs to consume all the elements before it.
- I haven't actually benchmarked this, but I would expect it's faster.
> Faster geometry indexing

- py-geopolars/example.py
- py-geopolars/python/geopolars/internals/geodataframe.py
- py-geopolars/src/api.rs
This PR adresses two things
- Fix example.py as this wasn't working. Now it returns correct centroid of dataframe. Previously it failed on import because centroid is a method on GeoSeries.
- GeoSeries.get_column("geometry") was returning Series instead of GeoSeries. This pr modify get_column to return GeoSeries when requested column is geo column
> Fix python example, return GeoSeries from get_column

- Cargo.lock
- geopolars/Cargo.toml
- geopolars/benches/explode.rs
- geopolars/src/geoseries.rs
Closes #26 by implementing an `explode_geometries` method that takes a `GeoSeries` with multipart geometries and return a `GeoSeries` with those geometries split into multiple individual geometries.
I've taken the approach suggested in the original issue, of iterating through the geometries and appending them to a new series.
I've added a test cribbed from the `geopandas` example to prove this works and a very minimal docstring, also copied from `geopandas`.
A few things to note:
- I went with `explode_geometries` instead of `explode` because when I used `explode` I was just getting the `polars` method of the same name. This is probably just ignorance on my part!
- I'm not handling  `Geometry::GeometryCollection` because I wasn't sure if I should be but I could do this recursively, if I …
> Implement `explode_geometries` method

- Cargo.lock
- geopolars/src/geoseries.rs
- py-geopolars/python/geopolars/internals/geoseries.py
- py-geopolars/src/api.rs
- py-geopolars/src/ffi.rs
- py-geopolars/src/geoseries.rs
- py-geopolars/tests/unit/conftest.py
- Implementation of 1:1 distance on GeoSeries
- Fix deprecated in ffi acquire_gil
- Always return python GeoSeries when using getitem
- Fix typing in test fixture
> Implementation of distance on GeoSeries

- .github/workflows/python-wheels.yml
- py-geopolars/Cargo.lock
- py-geopolars/Cargo.toml
- py-geopolars/python/geopolars/internals/geoseries.py
- py-geopolars/src/api.rs
- py-geopolars/src/geoseries.rs
Our current build process fails on PROJ
https://github.com/geopolars/geopolars/actions/runs/3202260055/jobs/5231061997, https://github.com/geopolars/geopolars/pull/109#issuecomment-1247993082
We should re-enable proj whenever we figure out how to build it correctly in wheels
> chore(Python): Disable proj (for now)

- .github/workflows/python-wheels.yml
Originally I thought there was a bug in maturin that incorrectly used the x86 name when building arm64 wheels, but it appears that bug is gone now. Building x86 and arm wheels separately means that more files are produced, but each one is half the size.
> chore(python): build arm64 wheels instead of universal2

- .vscode/settings.json
- py-geopolars/.vscode/settings.json
- wasm-geopolars/.vscode/settings.json
Store project-specific vscode settings for the [peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) plugin so that the language/plugin context is derived. Uses https://github.com/ozh/github-colors/blob/master/colors.json, so Rust, Python, and JS are reflected as a github citizen would expect
> chore, development: Set vscode window colors by language color

- py-geopolars/pyproject.toml
The new BinaryArray support is great but a breaking change for us. Issue tracked in #122 to be implemented whenever a new polars rust release is out
> pin polars to 0.14.18

- .github/workflows/python.yml
- py-geopolars/build.requirements.txt
- py-geopolars/pyproject.toml
In line with Numpy suggestions and geopandas/pyproj.
This also makes https://github.com/geopolars/geopolars/pull/148 easier, because our tests currently check for parity between the content of our datasets and what geopandas has. Geopandas updated its included datasets recently, but python 3.7 brings in an older version of geopandas with the old version of included datasets
See:
- https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule
- https://github.com/geopandas/geopandas/issues/2391
- https://github.com/geopandas/geopandas/pull/2398
> Drop support for 3.7

- .github/workflows/python.yml
- py-geopolars/Cargo.toml
- py-geopolars/pyproject.toml
This PR turns on [`abi3` support in pyo3](https://pyo3.rs/v0.17.2/building_and_distribution.html#py_limited_apiabi3), which means that we only need to build one wheel per platform (!!). That should be easier to manage and allow faster wheel building on CI.
a little (unscientific) perf testing on this below seems to show that there's no obvious difference in perf between python-version-specific wheels and abi3 wheels. This aligns with the hypothesis in https://github.com/pola-rs/polars/issues/5049#issuecomment-1263855313 that `abi3` should be ok because very little rust is actually touching the python api
```
maturin build --release
pyenv local 3.10.8
python -m venv env_310
source ./env_310/bin/activate
pip install ./target/wheels/geopolars-0.1.0a3-cp38-abi3-macosx_10_7_x86_64.whl
pip …
```
> Build `abi3` wheels for simplicity

- py-geopolars/Cargo.toml
- py-geopolars/docs/source/reference/index.rst
- py-geopolars/python/geopolars/__init__.py
- py-geopolars/python/geopolars/internals/geoseries.py
- py-geopolars/src/api.rs
- py-geopolars/src/lib.rs
Taken from rtoml: https://github.com/samuelcolvin/rtoml/blob/d7647396229d1a01369bca82bec5713ff51034cb/Cargo.toml#L16
This is nice to ensure that the internal rust-python bindings are actually marked as private
> Python: add underscore to internal rust bindings

- geopolars/benches/affine.rs
- geopolars/src/geoarrow/linestring/array.rs
- geopolars/src/geoarrow/point/array.rs
- geopolars/src/geoarrow/polygon/array.rs
- geopolars/src/ops/affine.rs
- Affine transform for geoarrow points
- helpers for iterating over coordinates
Benchmark:
```
translate               time:   [117.52 µs 118.78 µs 120.40 µs]
translate geoarrow      time:   [5.6917 µs 5.7521 µs 5.8163 µs]
```
> Affine transform geoarrow point

- geopolars/geopolars-arrow/src/linestring/array.rs
- geopolars/geopolars-arrow/src/linestring/scalar.rs
- geopolars/geopolars-arrow/src/multilinestring/array.rs
- geopolars/geopolars-arrow/src/multilinestring/scalar.rs
- geopolars/geopolars-arrow/src/multipoint/array.rs
- geopolars/geopolars-arrow/src/multipoint/scalar.rs
- geopolars/geopolars-arrow/src/multipolygon/array.rs
- geopolars/geopolars-arrow/src/multipolygon/scalar.rs
- geopolars/geopolars-arrow/src/point/array.rs
- geopolars/geopolars-arrow/src/point/scalar.rs
- geopolars/geopolars-arrow/src/polygon/array.rs
- geopolars/geopolars-arrow/src/polygon/mod.rs
- geopolars/geopolars-arrow/src/polygon/scalar.rs
- geopolars/geopolars-arrow/src/polygon/util.rs
move the conversion from geoarrow -> geo to the struct level, so it's useful when you only have the single geometry object
> refactor geoarrow scalar structs with better scalar functionality

- .github/workflows/python-wheels.yml
I noticed in https://github.com/geopolars/geopolars/pull/225 that the wheel builds were already failing because we switched the python build to Poetry in https://github.com/geopolars/geopolars/pull/216 but the wheel build was still trying to install from `build.requirements.txt`
> Update wheel build for poetry
